if __name__ == '__main__':
    mstr="good good study,day day up"
    mcount=mstr.count("good")
    print(mcount)
    kk=mstr.count("a")
    print(kk)
    qq=mstr.count("oo")
    print(qq)
    ww=mstr.count("d")
    print(ww)
    ee=mstr.count("g",3)
    print(ee)
    rr=mstr.count("d",10)
    print(rr)
    tt=mstr.count("da",5,20)
    print(tt)
    yy=mstr.count("a",3,15)
    print(yy)